# Generated by Django 4.2.5 on 2023-09-28 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_pessoa_options_pessoa_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_contratacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
