# Generated by Django 4.2.5 on 2023-09-29 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_funcionario_data_contratacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_contratacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
