# Generated by Django 4.2.5 on 2023-09-29 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_alter_funcionario_data_contratacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['matricula'], 'verbose_name': 'funcionario'},
        ),
    ]
